stages:
  - tests
tests_dev:
  stage: tests
  script:
    - echo "Testing fregate $(cat version.txt) $(date +%F\ %D)" >> /var/log/gitci.log
    - chmod 600 .fregate.d/id_rsa
    - pip3 install --user -e .
    - fregate -h
    - fregate -c tests/testinfra.yml up -d
    - fregate -c tests/testinfra.yml down
    - fregate -c tests/testinfra.yml clean
  only:
    - dev
  tags:
    - tests
