apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: default
  spec:
    rules:
    - http:
        paths:
        - backend:
            nameSpace: kube-system
            serviceName: kibana-logging
            servicePort: 5601
          path: /logs
